source:       app
baseurl:      ""

markdown:   kramdown
permalink:  pretty
exclude:
  - assets/styles
  - README.md
  - assets/img/img-src

google_analytics: UA-123168500-1

default_locale:     "en"
authorized_locales: ["en", "fr"]
locale_names:
  en: "English"
  fr: "Fran√ßais"

collections:
  disease:
    output: true
  action:
    output: true
  message:
    output: true
